version: '3'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  warehouse-admin:
    container_name: warehouse-admin
    build: ./warehouse-admin
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto

  client1:
    container_name: client-1
    build: ./client1
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mosquitto

  client2:
    container_name: client-2
    build: ./client2
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mosquitto

networks:
  default:
    driver: bridge
