version: '3'

services:
  mosquitto:
    container_name: mosquitto-event-broker
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  warehouse-service:
    container_name: warehouse-service
    build: ./warehouse-service
    restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - mosquitto

  client1:
    container_name: client-1
    build: ./client1
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mosquitto

  client2:
    container_name: client-2
    build: ./client2
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mosquitto

  master-web-service:
    container_name: master-web-service
    build: ./master-web-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - mosquitto

  order-service:
    container_name: order-service
    build: ./order-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - mosquitto

  delivery-service:
    container_name: delivery-service
    build: ./delivery-service
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - mosquitto

networks:
  default:
    driver: bridge
